package com.tutor.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ACCOUNT".
 */
public class Account {

    /** Not-null value. */
    private String id;
    private Integer memberId;
    private Integer role;
    private Integer status;
    private String email;
    private String pswd;
    private String phone;
    private String hkidNumber;
    private String residentialAddress;
    private String facebookId;
    private String imAccount;
    private String imPswd;
    private String token;
    private String createdTime;
    private String identityCode;
    private String alertTitle;
    private String alertContent;
    private String alertLink;

    public Account() {
    }

    public Account(String id) {
        this.id = id;
    }

    public Account(String id, Integer memberId, Integer role, Integer status, String email, String pswd, String phone, String hkidNumber, String residentialAddress, String facebookId, String imAccount, String imPswd, String token, String createdTime, String identityCode, String alertTitle, String alertContent, String alertLink) {
        this.id = id;
        this.memberId = memberId;
        this.role = role;
        this.status = status;
        this.email = email;
        this.pswd = pswd;
        this.phone = phone;
        this.hkidNumber = hkidNumber;
        this.residentialAddress = residentialAddress;
        this.facebookId = facebookId;
        this.imAccount = imAccount;
        this.imPswd = imPswd;
        this.token = token;
        this.createdTime = createdTime;
        this.identityCode = identityCode;
        this.alertTitle = alertTitle;
        this.alertContent = alertContent;
        this.alertLink = alertLink;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    public Integer getMemberId() {
        return memberId;
    }

    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    public Integer getRole() {
        return role;
    }

    public void setRole(Integer role) {
        this.role = role;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPswd() {
        return pswd;
    }

    public void setPswd(String pswd) {
        this.pswd = pswd;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getHkidNumber() {
        return hkidNumber;
    }

    public void setHkidNumber(String hkidNumber) {
        this.hkidNumber = hkidNumber;
    }

    public String getResidentialAddress() {
        return residentialAddress;
    }

    public void setResidentialAddress(String residentialAddress) {
        this.residentialAddress = residentialAddress;
    }

    public String getFacebookId() {
        return facebookId;
    }

    public void setFacebookId(String facebookId) {
        this.facebookId = facebookId;
    }

    public String getImAccount() {
        return imAccount;
    }

    public void setImAccount(String imAccount) {
        this.imAccount = imAccount;
    }

    public String getImPswd() {
        return imPswd;
    }

    public void setImPswd(String imPswd) {
        this.imPswd = imPswd;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime;
    }

    public String getIdentityCode() {
        return identityCode;
    }

    public void setIdentityCode(String identityCode) {
        this.identityCode = identityCode;
    }

    public String getAlertTitle() {
        return alertTitle;
    }

    public void setAlertTitle(String alertTitle) {
        this.alertTitle = alertTitle;
    }

    public String getAlertContent() {
        return alertContent;
    }

    public void setAlertContent(String alertContent) {
        this.alertContent = alertContent;
    }

    public String getAlertLink() {
        return alertLink;
    }

    public void setAlertLink(String alertLink) {
        this.alertLink = alertLink;
    }

}
