package com.tutor.model;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountDaoConfig;
    private final DaoConfig iMMessageDaoConfig;

    private final AccountDao accountDao;
    private final IMMessageDao iMMessageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        iMMessageDaoConfig = daoConfigMap.get(IMMessageDao.class).clone();
        iMMessageDaoConfig.initIdentityScope(type);

        accountDao = new AccountDao(accountDaoConfig, this);
        iMMessageDao = new IMMessageDao(iMMessageDaoConfig, this);

        registerDao(Account.class, accountDao);
        registerDao(IMMessage.class, iMMessageDao);
    }
    
    public void clear() {
        accountDaoConfig.getIdentityScope().clear();
        iMMessageDaoConfig.getIdentityScope().clear();
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

    public IMMessageDao getIMMessageDao() {
        return iMMessageDao;
    }

}
