package com.tutor.model;

import java.io.Serializable;
import java.util.Date;

import com.tutor.params.Constants;
import com.tutor.util.DateTimeUtil;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * 网络消息实体
 * 
 * Entity mapped to table "IMMESSAGE".
 */
public class IMMessage implements Serializable, Comparable<IMMessage> {

	private static final long serialVersionUID = 1L;
	// 消息是否读取状态
	public static final int READ_STATUS_READ = 0;
	public static final int READ_STATUS_UNREAD = 1;
	public static final int READ_STATUS_All = 2;
	public static final int READ_STATUS_ARRAY = 3;
	public static final int READ_STATUS_UNARRAY = 4;
	// 消息是否发送成功
	public static final int SEND_STATUS_SUCCESS = 0;
	public static final int SEND_STATUS_ERROR = 1;
	// 网络消息类型
	public static final int MESSAGE_TYPE_ADD_FRIEND = 1;// 好友请求
	public static final int MESSAGE_TYPE_SYS_MSG = 2; // 系统消息
	public static final int MESSAGE_TYPE_CHAT_MSG = 3;// 聊天消息
	// 聊天消息来源状态
	public static final int CHAT_MESSAGE_TYPE_RECEIVE = 0;
	public static final int CHAT_MESSAGE_TYPE_SEND = 1;
	/** Not-null value. id */
	private String id;
	/**
	 * 消息发送状态
	 */
	private Integer sendStatus;
	private String title;
	/** Not-null value. */
	private String content;
	private String time;
	/** Not-null value. 存在本地，表示与谁聊天 */
	private String fromSubJid;
	/** Not-null value. */
	private String toJid;
	private Integer readStatus;
	private String noticeTime;
	private Integer noticeSum;
	/**
	 * 消息类型 1.好友请求 2.系统消息3.聊天消息
	 */
	private Integer noticeType;
	/**
	 * 聊天消息的来源状态 0:接受 1：发送
	 */
	private Integer msgType;

	public IMMessage() {
		sendStatus = SEND_STATUS_SUCCESS;
		msgType = 0;
	}

	public IMMessage(String id) {
		this.id = id;
		sendStatus = SEND_STATUS_SUCCESS;
		msgType = 0;
	}

	public IMMessage(String id, Integer sendStatus, String title, String content, String time, String fromSubJid, String toJid, Integer readStatus, String noticeTime, Integer noticeSum,
			Integer noticeType, Integer msgType) {
		this.id = id;
		this.sendStatus = sendStatus;
		this.title = title;
		this.content = content;
		this.time = time;
		this.fromSubJid = fromSubJid;
		this.toJid = toJid;
		this.readStatus = readStatus;
		this.noticeTime = noticeTime;
		this.noticeSum = noticeSum;
		this.noticeType = noticeType;
		this.msgType = msgType;
	}

	/** Not-null value. */
	public String getId() {
		return id;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setId(String id) {
		this.id = id;
	}

	public Integer getSendStatus() {
		return sendStatus;
	}

	public void setSendStatus(Integer sendStatus) {
		this.sendStatus = sendStatus;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	/** Not-null value. */
	public String getContent() {
		return content;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setContent(String content) {
		this.content = content;
	}

	public String getTime() {
		return time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	/** Not-null value. */
	public String getFromSubJid() {
		return fromSubJid;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setFromSubJid(String fromSubJid) {
		this.fromSubJid = fromSubJid;
	}

	/** Not-null value. */
	public String getToJid() {
		return toJid;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setToJid(String toJid) {
		this.toJid = toJid;
	}

	public Integer getReadStatus() {
		return readStatus;
	}

	public void setReadStatus(Integer readStatus) {
		this.readStatus = readStatus;
	}

	public String getNoticeTime() {
		return noticeTime;
	}

	public void setNoticeTime(String noticeTime) {
		this.noticeTime = noticeTime;
	}

	public Integer getNoticeSum() {
		return noticeSum;
	}

	public void setNoticeSum(Integer noticeSum) {
		this.noticeSum = noticeSum;
	}

	public Integer getNoticeType() {
		return noticeType;
	}

	public void setNoticeType(Integer noticeType) {
		this.noticeType = noticeType;
	}

	public Integer getMsgType() {
		return msgType;
	}

	public void setMsgType(Integer msgType) {
		this.msgType = msgType;
	}

	/**
	 * 按时间排序
	 */
	@Override
	public int compareTo(IMMessage otherMessage) {
		if (null == otherMessage || null == this.getTime() || null == otherMessage.getTime()) {
			return 0;
		}
		String format = null;
		String time1 = "";
		String time2 = "";
		if (this.getTime().length() == otherMessage.getTime().length() && this.getTime().length() == 23) {
			time1 = this.getTime();
			time2 = otherMessage.getTime();
			format = Constants.General.MS_FORMART;
		} else {
			time1 = this.getTime().substring(0, 19);
			time2 = otherMessage.getTime().substring(0, 19);
		}
		Date da1 = DateTimeUtil.str2Date(time1, format);
		Date da2 = DateTimeUtil.str2Date(time2, format);
		if (da1.before(da2)) {
			return -1;
		}
		if (da2.before(da1)) {
			return 1;
		}
		return 0;
	}

	@Override
	public String toString() {
		return "IMMessage [id=" + id + ", sendStatus=" + sendStatus + ", title=" + title + ", content=" + content + ", time=" + time + ", fromSubJid=" + fromSubJid + ", toJid=" + toJid
				+ ", readStatus=" + readStatus + ", noticeTime=" + noticeTime + ", noticeSum=" + noticeSum + ", noticeType=" + noticeType + ", msgType=" + msgType + "]";
	}
}
